### ISSUE TITLE
webpack 5 problem

### ISSUE THREAD

**Issue by amirjr1378** [SolidZORO/next-plugin-antd-less#41] opened 2021-04-20 11:59 UTC
when i use  future: {
    webpack5: true,
  }
yarn build or dev give me error like screenshot
![image](https://user-images.githubusercontent.com/49060396/115392210-8d9f0300-a1f5-11eb-8592-e525114208da.png)

**Comment by SolidZORO** [comment] 2021-04-20 13:31
Wait for Next.js to enable webpack5 by default, and I'll support it.

**Comment by elado** [comment] 2021-04-20 18:40
I also needed webpack 5 support, ended up creating a package: 

* https://github.com/elado/next-with-less
* https://www.npmjs.com/package/next-with-less

**Comment by dryleaf** [comment] 2021-04-28 08:41
I am now going to switch to @elado package, I am dying for `webpack5` support. I cannot use other plugins due to errors of `next-plugin-antd-less`.

**Comment by lgenzelis** [comment] 2021-04-28 21:14
Since 10.2 webpack is enabled by default 🎉

**Comment by dryleaf** [comment] 2021-04-28 23:07
@lgenzelis What do you mean it is enabled by default? What I know is Next.js team plans to enable webpack 5 by default from version 11+.

**Comment by dryleaf** [comment] 2021-04-28 23:21
@SolidZORO Please enable webpack 5 on this package. @lgenzelis Is right, Next.js 10.2 is released with webpack 5 enabled by default. https://nextjs.org/blog/next-10-2

**Comment by SolidZORO** [comment] 2021-04-29 04:49
I just tried it and found that removing `handleAntdInServer` is working on `dev`, but not `build`. this will take some time to fix, especially since I have to get familiar with webpack5. so I'll deal with it later.

**Comment by SolidZORO** [comment] 2021-04-29 05:25
> I also needed webpack 5 support, ended up creating a package: 
> 
> 
> 
> * https://github.com/elado/next-with-less
> 
> * https://www.npmjs.com/package/next-with-less

hi，this plugin working at next.js 10.2 with antd less?

**Comment by dryleaf** [comment] 2021-04-29 05:37
I tried that plugin with antd less, it doesn't not work for me. Because the antd css styles are not applied and did not find a way to inject with babel plugin. Your package is the only thing that works for me. You just need to work on webpack 5 support for it.

**Comment by SolidZORO** [comment] 2021-04-29 06:01
@dryleaf  Yes, I understand. I looked at webpack5 today and a lot of the syntax has changed so that some of the dependencies like `null-loader` are also not available anymore, officially they say you can use `resolve.alias = false` instead, but I don't know how to go about completing this.

So for now I'll keep it webpack4 only, and when I figure out how to migrate to webpack5, I'll finish it with webpack5 compatibility, but I'm not sure how long it will take, maybe up to a month.

**Comment by elado** [comment] 2021-04-29 16:16
> hi，this plugin working at next.js 10.2 with antd less?

Yes. Tested with 10.1 and 10.2 and antd. There could be some cases/configs I haven't handled. I tried to keep the package as small and as resilient to next changes as possible.

**Comment by lgenzelis** [comment] 2021-04-29 16:33
> I tried that plugin with antd less, it doesn't not work for me. Because the antd css styles are not applied and did not find a way to inject with babel plugin. Your package is the only thing that works for me. You just need to work on webpack 5 support for it.

@dryleaf I created a [PR](https://github.com/elado/next-with-less/pull/2) for @elado's plugin, to add an option to customize antd variables. So hopefully that'll be solved soon.

**Closed** 2021-05-09 11:15 UTC

**Comment by amirjr1378** [comment] 2021-05-10 12:43
yes sir

**Comment by ianldgs** [comment] 2021-05-10 13:34
I can confirm: it works and the build went down 1 minute for me.
Thanks for the great plugin and this update, @amirjr1378!
